[project]
name = "repl-nix-pdf-redactor"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "fitz>=0.0.1.dev2",
    "pymupdf==1.25.0",
    "regex==2024.11.6",
    "streamlit>=1.41.1",
]
